In [2]:
import numpy as np

### Q-01: Create a 3x3 numpy array of the True's

In [4]:
x1 = np.ones(9, dtype = bool).reshape((3, 3))
print(x1)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Q-02: Extract all odd numbers from arrays

In [7]:
x2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x2[x2 % 2 == 1])

array([1, 3, 5, 7, 9])

### Q-03: Replace all even numbers in above array with -5

In [10]:
i = x2[x2 % 2 == 0]
x2[i] = -5
print(x2)

[-5  1 -5  3 -5  5 -5  7 -5  9]


### Q-04: Reshape an array

In [17]:
x3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(2,5)
print(x3)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Q-05: How to get the positions where elements of two arrays match

In [24]:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7,4, 9, 4, 9, 8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

### Q-06: Swap columns 1 and 2 in the array

In [46]:
x4 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Before Array: \n',x4)
x4[:, [1, 0]] = x4[:, [0, 1]]
print('After Swaping: \n',x4)

Before Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After Swaping: 
 [[2 1 3]
 [5 4 6]
 [8 7 9]]


### Q-07: Reversing the columns of a 2D array

In [43]:
x5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x5[:,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

### Q-08: Create a 2D array of shape 5x3 to contain random decimals between 5 and 10

In [52]:
x6 = np.random.uniform(5, 10, size = (5, 3))
print(x6)

[[9.81563112 5.64092286 5.78754424]
 [6.08943806 6.87291264 8.84371292]
 [7.03570125 6.55387349 5.10886821]
 [7.11635764 7.47303321 5.42838729]
 [5.70329931 9.89253151 9.89198701]]


### Q-09: Create a 2D array with i on the border and 0 inside

In [78]:
x7 = np.ones((10, 10))
x7[1:-1, 1:-1]= 0
print(x7)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### Q-10: Use fancy indexing

In [73]:
x8 = np.array([[9, 1, 12, 3], [14, 15, 6, 7], [18, 9, 10, 11]])
x8[[0, 1, 2], [2, 0, 3]]

array([12, 14, 11])